# Generated by Django 6.0.5 on 2026-05-31 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id_entrenadores', models.AutoField(primary_key=True, serialize=False)),
                ('id_adminitrador', models.IntegerField(blank=True, null=True)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=150, null=True)),
                ('gimnasio_id', models.IntegerField(blank=True, null=True)),
                ('anios_experiencia', models.IntegerField(blank=True, null=True)),
                ('foto_url', models.CharField(blank=True, max_length=255, null=True)),
                ('aprovacion_entrenador', models.BooleanField(default=False)),
                ('hoja_vida', models.CharField(blank=True, max_length=255, null=True)),
                ('calificacion_prom', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'entrenadores',
            },
        ),
        migrations.CreateModel(
            name='SolicitudEntrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField(blank=True, null=True)),
                ('gimnasio_id', models.IntegerField(blank=True, null=True)),
                ('nombres_apellidos', models.CharField(blank=True, max_length=200, null=True)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('experiencia', models.TextField(blank=True, null=True)),
                ('sobre_mi', models.TextField(blank=True, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=150, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('suspendido', 'Suspendido')], default='pendiente', max_length=20)),
                ('revisado_por', models.BooleanField(default=False)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'solicitudes_entrenador',
            },
        ),
        migrations.CreateModel(
            name='EntrenadorDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(blank=True, max_length=80, null=True)),
                ('nombre_archivo', models.CharField(blank=True, max_length=150, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('entrenador', models.ForeignKey(blank=True, db_column='entrenador_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.entrenador')),
            ],
            options={
                'db_table': 'entrenador_documentos',
            },
        ),
    ]
