# Generated by Django 6.0.5 on 2026-05-28 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('seccion_lugar', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Nutricion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('objetivo', models.TextField(blank=True, null=True)),
                ('imagen_url', models.CharField(blank=True, max_length=255, null=True)),
                ('autor_id', models.IntegerField(blank=True, null=True)),
                ('publicado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nutrición',
                'verbose_name_plural': 'Nutriciones',
                'db_table': 'nutricion',
            },
        ),
        migrations.CreateModel(
            name='ComentarioComunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField()),
                ('contenido', models.TextField()),
                ('calificacion', models.IntegerField(blank=True, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios', to='blog.categoria')),
            ],
            options={
                'verbose_name': 'Comentario Comunidad',
                'verbose_name_plural': 'Comentarios Comunidad',
                'db_table': 'comentarios_comunidad',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('encabezado', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen_principal', models.CharField(blank=True, max_length=255, null=True)),
                ('autor_id', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(default='borrador', max_length=20)),
                ('vistas', models.IntegerField(default=0)),
                ('publicado_en', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='noticias', to='blog.categoria')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'db_table': 'noticias',
            },
        ),
        migrations.CreateModel(
            name='ArticuloSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_seccion', models.CharField(blank=True, max_length=200, null=True)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('imagen_url', models.CharField(blank=True, max_length=255, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secciones', to='blog.noticia')),
            ],
            options={
                'verbose_name': 'Artículo Sección',
                'verbose_name_plural': 'Artículos Secciones',
                'db_table': 'articulos_secciones',
            },
        ),
        migrations.CreateModel(
            name='DietaComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_comida', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comidas', to='blog.nutricion')),
            ],
            options={
                'verbose_name': 'Dieta Comida',
                'verbose_name_plural': 'Dieta Comidas',
                'db_table': 'dieta_comidas',
            },
        ),
        migrations.CreateModel(
            name='RespuestaComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField()),
                ('contenido', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='blog.comentariocomunidad')),
            ],
            options={
                'verbose_name': 'Respuesta Comentario',
                'verbose_name_plural': 'Respuestas Comentario',
                'db_table': 'respuestas_comentario',
            },
        ),
    ]
