# Generated by Django 6.0.5 on 2026-06-01 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SedeGimnasio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('nit', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('correo', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('agregar_img', models.CharField(blank=True, max_length=255, null=True)),
                ('agregar_sede', models.CharField(blank=True, max_length=255, null=True)),
                ('aprovacion_entrenadores', models.BooleanField(default=False)),
                ('calificacion_prom', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('total_resenas', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('administrador_id', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sede Gimnasio',
                'verbose_name_plural': 'Sedes Gimnasios',
                'db_table': 'sedes_gimnasios',
            },
        ),
        migrations.CreateModel(
            name='ResenaGimnasio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_id', models.IntegerField()),
                ('calificacion', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('gimnasio', models.ForeignKey(db_column='gimnasio_id', on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='gimnasios.sedegimnasio')),
            ],
            options={
                'verbose_name': 'Reseña Gimnasio',
                'verbose_name_plural': 'Reseñas Gimnasio',
                'db_table': 'resenas_gimnasio',
            },
        ),
        migrations.CreateModel(
            name='GimnasioClase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_clase', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('gimnasio', models.ForeignKey(db_column='gimnasio_id', on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='gimnasios.sedegimnasio')),
            ],
            options={
                'verbose_name': 'Gimnasio Clase',
                'verbose_name_plural': 'Gimnasio Clases',
                'db_table': 'gimnasio_clases',
            },
        ),
    ]
